# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aigotchi < Formula
  desc "Terminal Tamagotchi that grows with your Claude Code token usage"
  homepage "https://github.com/egoomoy/aigotchi"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/egoomoy/aigotchi/releases/download/v0.1.0/aigotchi_darwin_amd64.tar.gz"
      sha256 "bd1d7321626cfb2f8183e29cfbf1463adf631feea7db34f10e8113f2c1b632af"

      define_method(:install) do
        bin.install "aigotchi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/egoomoy/aigotchi/releases/download/v0.1.0/aigotchi_darwin_arm64.tar.gz"
      sha256 "9d96fb44a4a534c25020c056dfb63505d98153f32df7f926fce7bd23750f7ab1"

      define_method(:install) do
        bin.install "aigotchi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/egoomoy/aigotchi/releases/download/v0.1.0/aigotchi_linux_amd64.tar.gz"
      sha256 "3598c14a6916c80006e67c264a1cd167aa4409a8b41a3a9f96d37ee244b6e212"
      define_method(:install) do
        bin.install "aigotchi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/egoomoy/aigotchi/releases/download/v0.1.0/aigotchi_linux_arm64.tar.gz"
      sha256 "e16d3afb315dbb076f7f817873ed0e66f84dc6dd29cf3ea259f07af8ff201b9b"
      define_method(:install) do
        bin.install "aigotchi"
      end
    end
  end
end
